export const RuntimeConfiguration = {
  API_HOST_URL: process.env.NEXT_PUBLIC_RUNTIME_API_HOSTNAME!,
  CHAIN_ID: process.env.NEXT_PUBLIC_RUNTIME_CHAINID!,
  CONTENT_URL: process.env.NEXT_PUBLIC_RUNTIME_CONTENT_URL!,
  PRIVACY_URL: process.env.NEXT_PUBLIC_RUNTIME_PRIVACY_URL!,
  TERMS_URL: process.env.NEXT_PUBLIC_RUNTIME_TERMS_URL!,
  CROSSMINT_API: process.env.NEXT_PUBLIC_CROSSMINT_API_KEY,
  NETWORK_ID: process.env.NEXT_PUBLIC_NETWORK_ID,
  ORG_ID: process.env.NEXT_PUBLIC_ORG_ID,
  CROSSMINT_ENV: process.env.NEXT_PUBLIC_CROSSMINT_ENV,
  PAPER_CLIENT_ID: process.env.NEXT_PUBLIC_PAPER_CLIENT_ID,
  NETWORK_NAME: process.env.NEXT_PUBLIC_NETWORK_NAME,
  GOOGLE_ANALYTICS_TRACKING_ID:
    process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING_ID,
  GOOGLE_TAG_MANAGER_ID: process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID,
  WALLET_CONNECT_PROJECT_ID:
    process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID ?? "",
  ITEM_ID: process.env.NEXT_PUBLIC_ITEM_ID ?? "",
  CLIENT_ID: process.env.NEXT_PUBLIC_CLIENT_ID ?? "",
  ACTIVE_CHAIN_ID: process.env.NEXT_PUBLIC_ACTIVE_CHAIN_ID ?? "sepolia",
  TOKEN_GATING_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_TOKEN_GATING_CONTRACT_ADDRESS ?? "",
  TOKEN_GATING_GROUP_ID: process.env.NEXT_PUBLIC_TOKEN_GATING_GROUP_ID ?? "",
  TOKEN_GATING_TOKEN_ID: process.env.NEXT_PUBLIC_TOKEN_GATING_TOKEN_ID ?? "",
  TOKEN_GATING_RULE_ID: process.env.NEXT_PUBLIC_TOKEN_GATING_RULE_ID ?? "",
};
